[package]
name = "three-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["json"] }
tokio = { version = "1.44.2", features = ["full"] }


[[bin]]
name = "three-rs"
path = "three-rs.rs"
